spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://27.122.250.174:3306/userdb
    username: joo0
    password: wndud123
  jpa:
#   generate-ddl: true
    show-sql: false
    database: mysql